cordova-src/ios/BNCDevice.m

reset universal_link_url/link_click_identifier after consumed

---

.gitignore
README.md
plugin.xml
testbed/config.xml
testbed/init.sh

updated README. replace branch keys. updated init.sh.

---

src/ios/AppDelegate+BranchSdk.m
src/ios/BranchSDK.h

fix for #72 
- added extra notification post/call to allow plugins to use openUrl without conflicts

fix for openUrl() method conflict when using facebook plugins

---

README.md

Remove old BRANCH_TEST_KEY variable and simplify App/Universal links

---

plugin.xml
src/android/io/branch/BranchSDK.java

Fixed missing ES6-Promise support for Cordova web view components.

[FIX] Branch plugin not initializing on Android 4.2.2

---

src/android/io/branch/BranchSDK.java

Implemented threading on Cordova methods to avoid bottleneck issues with the `WebCore` thread.

[PERF] Implemented threading on methods

---

src/android/io/branch/BranchSDK.java

Fix shareSheet call in Android.

[FIX] Android build error for shareSheet method

---

src/android/io/branch/BranchSDK.java
testbed/www/js/index.js

Follow-up commit for Android in related to #92 .

[FEAT] On error handler for handling deep link urls.

---

src/android/io/branch/BranchSDK.java

@renesansz This will take care of the issue reported in
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/112

Support for legacy share sheets

---

README.md

Removed NPM installation method.

[CHORE] Removed NPM installation method.

---

README.md

Updated `DeepLinkHandler` usage.

[CHORE] Updated README.

---

src/android/io/branch/BranchSDK.java
src/ios/AppDelegate+BranchSdk.m
src/ios/BranchSDK.m
www/branch.js

Filtered out the fixes from https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/118

Filtered fixes from Hurdlr

---

README.md

Corrects the syntax error in showShareSheet()

Update Read Me for Share sheet

---

README.md

Updated parameters descriptions.

[CHORE] Updated parameter descriptions for control params

---

hooks/lib/android/manifestWriter.js

@renesansz This should resolve the autoVerify error. Basically, autoVerify is not supported if build target is less than 23. This will check in the prepare hook. 
Resolves: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/50#issuecomment-214698624

Fix auto verify error

---

README.md

@renesansz something weird happened and this content disappeared. Can you just confirm that this is what it's actually supposed to be?

Re-add some missing content

---

README.md
src/ios/BranchSDK.h
src/ios/BranchSDK.m
testbed/www/js/index.js
www/branch.js

Implemented share sheet dismiss callback for iOS.

[FEAT] Implemented share sheet dismiss callback for iOS.

---

src/android/io/branch/BranchSDK.java
testbed/www/js/index.js
www/branch.js

This PR fixes the following:
- Fixed NonBranchLinkHandler wherein it should not be mandatory to be defined.
- Fixed string callback error for NonBranchLinkHandler in Java

[FIX] Fixed NonBranchLinkHandler when app is offline.

---

README.md
src/android/io/branch/BranchSDK.java

[FIX] alias, channel, feature, and stage aren't set when creating branch universal link.

[FIX] Missing properties when generating branch universal link

---

src/android/io/branch/BranchSDK.java

Fixed setContentType getting the wrong data type.

[FIX] Invalid data type being retrieved for setContentType.

---

src/android/io/branch/BranchSDK.java

Pull Request Changes:
* Fixed String syntax & conditional statement causing Android build to fail

[FIX] Android build error

---

src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.m

@amit-bansil Let's test new deployment with this when ready.

Should clear deep link even if Branch

---

plugin.xml
src/ios/dependencies/Branch-SDK/BNCConfig.h
src/ios/dependencies/Branch-SDK/BNCFabricAnswers.m
src/ios/dependencies/Branch-SDK/BNCPreferenceHelper.m
src/ios/dependencies/Branch-SDK/Branch.h
src/ios/dependencies/Branch-SDK/Branch.m
src/ios/dependencies/Branch.framework/Versions/A/Headers/BNCConfig.h
src/ios/dependencies/Branch.framework/Versions/A/Headers/Branch.h
tests-harness/config.xml
tests-harness/init.sh
tests/tests.js

Pull request changes:
* Updated unit-test methods
* Fixed unit-test for async methods

[CHORE] Updated unit test

---

README.md

fix: travis and NPM

---

README.md
src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.h
src/ios/BranchSDK.m
src/ios/dependencies/Branch-SDK/BNCConfig.h
src/ios/dependencies/Branch-SDK/BNCPreferenceHelper.h
src/ios/dependencies/Branch-SDK/BNCStrongMatchHelper.m
src/ios/dependencies/Branch-SDK/Branch.h
src/ios/dependencies/Branch-SDK/Branch.m
src/ios/dependencies/Branch-SDK/Requests/BranchInstallRequest.m
src/ios/dependencies/Branch.framework/Versions/A/Headers/BNCConfig.h
src/ios/dependencies/Branch.framework/Versions/A/Headers/BNCPreferenceHelper.h
src/ios/dependencies/Branch.framework/Versions/A/Headers/Branch.h
testbed/www/js/index.js
www/branch.js

feat: Add setDebug back

---

hooks.es6/beforePluginInstallHook.js
hooks/beforePluginInstallHook.js

**issue** https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/205
**jira** https://branch.atlassian.net/browse/AIS-63
**tested** complete branch deep linking experience

fix: moved node_modules from root directory to io.branch.sdk directory

---

DEVELOPING.md
plugin.template.xml
plugin.xml
testbed/www/js.es6/index.js
testbed/www/js/index.js

Fix ios frameworks and core spotlight

---

hooks.es6/beforePluginInstallHook.js
hooks/beforePluginInstallHook.js
package.json
plugin.template.xml
plugin.xml

https://branch.atlassian.net/browse/INTENG-2996
* error
* works
```bash
cordova platform remove ios;
cordova platform remove android;
cordova platform remove browser;
cordova platform add ios;
cordova platform add android;
cordova plugin remove io.branch.sdk;
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_icCccJIpd7GlYY5oOmoEtpafuDiuyXhT --variable URI_SCHEME=enefftest;
```
* breaks 
```bash
cordova platform remove ios;
cordova platform remove android;
cordova platform remove browser;
cordova plugin remove io.branch.sdk;
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_icCccJIpd7GlYY5oOmoEtpafuDiuyXhT --variable URI_SCHEME=enefftest;
cordova platform add ios;
cordova platform add android;
```

Fix before hook

---

README.md

Pull request changes:
* Fixed typo on the doc

fix: documentation fix

---

src/index.js

Feature check for window.clientInformation which is not available on some browsers like Firefox.

fix: feature check for window.clientInformation

---

examples/cordova1/platforms/android/app/src/main/assets/www/plugins/branch-cordova-sdk/src/index.js
examples/cordova1/platforms/ios/Cordova1/Plugins/branch-cordova-sdk/BranchSDK.m
examples/cordova1/platforms/ios/www/plugins/branch-cordova-sdk/src/index.js
examples/cordova1/plugins/branch-cordova-sdk/src/ios/BranchSDK.m
examples/ionic3/config.xml
examples/ionic3/src/pages/home/home.html
examples/ionic3/src/pages/home/home.ts
src/ios/BranchSDK.m

@aaaronlopez added v2 events in examples(cordova1 & ionic3) and a code change in ios(BranchSDK.m) file

added v2 Events in ionic3

---

src/scripts/hooks/beforePluginInstall.js

Fix https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/512

fix: async usage of installing npm dependencies

---

CHANGELOG.md

Missed updating the changelog.

SDK-173 missed updating the changelog.md

---

src/android/io/branch/BranchSDK.java

Stub Android CPID and LATD calls due to caching issues

bug(cpid-latd): stub cpid latd calls due to caching issue

---

package.json
plugin.xml
src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.m

somehow typos made it back into the iOS code

Release 4.1.1

---

plugin.xml
src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.m
src/scripts/hooks/beforePluginInstall.js
src/scripts/npm/setPluginVersion.js

SDK-849
Change Android traffic tagging API, report plugin version programmatically

Change Android API, report plugin version programmatically

---

src/index.js

Deprecate delay for apple search ads method SDK-884

Deprecate delay for apple search ads method SDK-884

---

CHANGELOG.md
package.json
plugin.xml

Update iOS SDK to 0.35.0

---

src/scripts/android/updateAssets.js
src/scripts/hooks/beforePrepare.js
src/scripts/ios/updatePbxproj.js
src/scripts/npm/processConfigXml.js

Add hooks to copy/include branch.json to assets/resources

Add hooks to copy/include branch.json to assets/resources

---

src/ios/BranchSDK.m

CORE-1898 correct signature as a quick fix.

---

package.json
plugin.xml
src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.m

Add content items support in sendBranchEvent
Remove sendCommerceEvent
Fix bug where custom data would clobber other fields when creating event in Android plugin
Update iOS SDK to 1.40.2
Update Android SDK to 5.0.15

Add content items support in sendBranchEvent

---

plugin.xml
src/ios/AppDelegate+BranchSdk.m
src/ios/BranchSDK.h
src/scripts/ios/updateHeaderPaths.js

SDK-2015 -- Bump iOS and Android versions
Updated the Branch SDKs for iOS to 2.2.0 and Android to 5.7.0
Keep Cordova up to date with the other SDKs.
Ensure there were no breaking changes from the native SDK updates.

[SDK-2015] Updated native SDKs

---

CHANGELOG.md
package.json
plugin.xml
src/android/io/branch/BranchSDK.java
src/ios/BranchSDK.h
src/ios/BranchSDK.m

Removed various deprecated methods and updates imports to use the latest Branch native SDKs.
Updating to the latest native SDKs required removing methods from the plugin as well.
Try out the `6.0.0-alpha.6` package in a Cordova test app on Android and iOS. Everything should build and run fine.

Remove methods that no longer exist in native SDKs

---

CHANGELOG.md
package.json
plugin.xml

* Update Android SDK to 5.12.3
* Update iOS SDK to 3.6.3

Release 6.3.0

---

CHANGELOG.md
package.json
plugin.xml

Updated the Android SDk to 5.12.4

Release 6.3.1 & updated Android version to 5.12.4

---

CHANGELOG.md
package.json
plugin.xml

* Update Android SDK to 5.13.0
* Update iOS SDK to 3.6.5

Release 6.4.0

---

src/android/io/branch/BranchSDK.java

#739 Fixing import in android/branch/BranchSDK.java
SDK-5.15.1 -- Wrong java import.

Fix import

---

CHANGELOG.md
plugin.xml

Release 6.5.1
