BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution

- plugin.xml
fix broken xml version in plugin.xml, which is causing problems in phonegap build and other build tools.
> fix broken xml version in plugin.xml

- plugin.xml
The unminified version of the build script was being referenced
> Possible fix for #19

- www/branch.js
removed setDebug condition for executing initSession
> removed setDebug requirement for initSession in plugin

- src/ios/BranchSDK.m
#52 DeepLinkHandler returns string instead of dictionary
> DeepLinkHandler now returns string instead of dictionary

- src/ios/BranchSDK.m
For #52.
The object passed by the `DeepLinkHandler` handler, in JavaScript, should actually be an `Object`. Android currently passes an `Object` via the handler, and iOS returns a string due to quotes around the text. I simply removed these quotes to allow JavaScript to teach the data passed as an `Object`.
> Proposed Change Implementation Example
>  ```javascript
> // New
> function DeepLinkHandler(data) {
>     // Do stuff with data here 
> }
>
> // Current
> function DeepLinkHandler(data) {
>     if(typeof data === 'string') {
>         data = JSON.parse(string);
>     }
> 
>     // Do stuff with data here 
> }
> ```
_I have yet to actually test this... I'm not set up in my environment currently... so don't merge till someone tests_
> Make our object passed by DeepLinkHandler (iOS) actually an object

- README.md
Looks like the NPM package is v2 as of a couple hours ago, and is that extra '/' in the prefix for the test environment necessary?
> NPM package is now on v2, and removing an extra '/'

- README.md
- src/android/io/branch/BranchSDK.java
Had some trouble with the Cordova SDK when testing with Android, so here are some fixes.
1. No more class-level callbackContext; individual callbackContexts are
passed between methods to ensure we don’t clobber the callbackContext
with two concurrent calls to execute()
2. logout, registerView, and userCompletedAction were missing callback
resolutions, so I added those. userCompletedAction’s logic is not
completely correct as it will always (early) resolve to “success” but
Branch.java in the Branch SDK does not expose a method that takes in a
listener for userCompletedAction that I saw.
3. Fixed CreditHistoryListener to reject a promise if there was a JSON
exception
4. Added properly evaluated callback to setIdentity
5. Updated Readme.md to match code for installation
> Fix callback concurrency issues; ensure more methods will resolve callbacks; do a best-case handling for userCompletedAction; update readme

- src/android/io/branch/BranchSDK.java
- src/ios/BranchSDK.m
Issues addressed in this PR:
Android:
1. getFirstReferringParams() and getLatestReferringParams() will now return boolean false when no params are available (trying to serialize a null will throw an exception) or when the received object is null. The behavior now matches iOS.
iOS:
1. initSession will now resolve a promise with the latest param data
2. logout now resolves a promise
3. userCompletedAction now resolves a promise, but like the Android equivalent, it is too early (e.g. before we receive confirmation from the server) but I didn’t see a method s.t. I could use a listener to wait for the response.
4. loadRewards() will now return just an int value instead of a JSON string; it is now consistent with Java
5. getCreditsHistory() will now return a straight array of entries instead of …
> Fixes for iOS plugin (& ensure consistency w/Android implementation)

- src/android/io/branch/BranchSDK.java
- src/ios/BranchSDK.m
Worth noting that it looks like doing the following:
initSession()
setDebug(true)
setDebug(false)
will currently leave the debug state as true since false is pretty much
a no-op. This commit at least fixes (on iOS) so that if you do
initSession() then setDebug(false), it doesn’t set debug mode to on.
Both platforms now return a proper bool value of true/false.
> resolve setDebug promise on Android & ios with passed-in value

- src/android/io/branch/BranchSDK.java
Fixed `initSession` on new intent handler wherein it doesn't pass any `callbackContext`.
> [FIX] Null callbackcontext for initSesison

- README.md
- src/android/io/branch/BranchSDK.java
- testbed/www/js/index.js
- www/branch.js
Added option for customizing share text.
> [FEAT] Added custom share text option.

- plugin.xml
Increased minimum Cordova build version to support 64-bit for iOS.
See this [article](http://phonegap.com/blog/2015/01/20/ios-64bit-support/)
> [FIX] Increased minimum Cordova build version.

- src/ios/BranchSDK.m
In regards to issue #116 .
Wherein `NSString` was not handled properly for null returns.
> [FIX] Issue with iOS crash which string value was not handled properly.

- hooks/lib/ios/xcodePreferences.js
Fixed hook script error for iOS build where v1.indexof() is not found.
> [FIX] Fixed hook script where node-version-compare()

- src/android/io/branch/BranchSDK.java
Addresses https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/160. The NonBranchLinkHandler was only called when there was an error. We need to actually call it when there's no Branch link : /
> Fix Android NonBranchLinkHandler

- src/ios/BranchSDK.m
The Header imported is not correct which causes a build error.
> Fixed Build Error - Incorrect Header

- .travis.yml
this will keep us from producing separate builds for each node version
> chore(travis): only build on node 6

- build-branch-extras.gradle
- plugin.xml
In reference to https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/208, it's super hard to fix library conflicts with the current method of dropping in the Android SDK. This creates a gradle extension file that can be easily changed in the platform directory.
@renesansz @amit-bansil
> fix: Create path for Crashlytics harmony

- .gitignore
- README.md
- package.json
- plugin.xml
- src/android/io/branch/BranchSDK.java
This change break the backward compatibility because the third parameter of showShareSheet action is now a JSON and not a String.
> fix: Remove hard coded strings when showing the showShareSheet

- plugin.template.xml
- plugin.xml
Fetching from npm assures always using the same version
(more stable and reproducible builds) and is generally much faster
than cloning from github (particularly in enterprise env
with private npm repo)
I opened this PR because today fetching the es6 plugin from github is failing a lot:
```
Installing "io.branch.sdk" for android
Fetching plugin "https://github.com/vstirbu/PromisesPlugin.git" via git clone
Failed to install 'io.branch.sdk':CordovaError: Failed to fetch plugin https://github.com/vstirbu/PromisesPlugin.git via git.
Either there is a connection problems, or plugin spec is incorrect:
Error: C:\Program Files (x86)\Git\bin\git.exe: Command failed with exit code 128 Error output:
...
fatal: unable to access 'https://github.com/vstirbu/PromisesPlugin.git/': Failed to connect to …
```
> feat: use es6-promise-plugin from npm instead of github

- src/ios/dependencies/Branch-SDK/BranchUniversalObject.m
This fix allows the ability to handle the shareTitle for email client and choose specific text when contentMetaData is provided from the UI call.
In reference to Android fix https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/aa2dfcc18d5c6d9e0c8105abf07aa5a535910ef5
> iOS fix shareTitle and shareText

- src/index.js
window.clientInformation && window.clientInformation.vendor still shows TypeError: deviceVendor is undefined. Resolved this.
> Handling Typeerror window.clientInformation: undefined

- src/ios/BranchSDK.m
The Android version of the plugin allows this behaviour so presumably iOS should as well.
> Fix: iOS disableTracking can now also be used to enable tracking

- src/android/dependencies/rules.gradle
This fixes an issue with older versions of cordova having issues resolving the branch aar.
> SDK-215 Use older gradle syntax for improved backwards compatibility

- src/scripts/ios/enableEntitlements.js
Fix distribution code signing identity in cordova-ios 5.0.1 / cordova 9.0.0 by defining either the Developer or Distribution identities depending on the configuration config name (Release/Debug)
Without this change distribution builds are configured to attempt a build with a debug/developer signing cert: https://github.com/apache/cordova-ios/issues/536#issuecomment-530135917
> Option 2: Configure the declaration of the code sign identity correctly

- src/scripts/android/updateAndroidManifest.js
This fixes https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/581 adding an optional uses-sdk tag from Android Manifest file.
This issue is an incompatibility between branch v3.2.0 and cordova-android@8.1.0
Steps to a successful install:
- `ionic start test tutorial --type=ionic-angular`
- cd into test project
- `ionic cordova platform add android` this should add cordova-android@8.1.0
- Add branch-cordova-sdk to config.xml using the following spec `git+https://github.com/adrianyg7/cordova-ionic-phonegap-branch-deep-linking-attribution.git` which is a fork of the v3.2.0 tag including the fix
```
<plugin name="branch-cordova-sdk" spec="git+https://github.com/adrianyg7/cordova-ionic-phonegap-branch-deep-linking-attribution.git" />
<branch-config> …
```
> ISSUE-581 Android Manifest uses-sdk tag optional

- README.md
As of version 2.7.1 android-prefix is no longer used
> Remove android-prefix from branch-config

- README.md
- package.json
- plugin.xml
* Drop required Cordova version to Cordova 8
* Cordova 8 doesn't correctly support CocoaPods
* An additional Cordova plugin is needed to fully support CocoaPods
This PR adds documentation to that effect and modifies the cordova minimum version to v8.
This working example is documented in [our repo in the cordova-8 branch](https://github.com/engineerapart/branch-cordova-helloworld/tree/example/cordova-8)
> Branch 4.1.x + Cordova 8: Document how it works

- package.json
- src/android/io/branch/BranchSDK.java
- src/ios/BranchSDK.m
Both onNewIntent and onResume events get fired when doing intra-app linking, and because we call initSession from onDeviceResume in Cordova, simply setting `intent.putExtra("branch_force_new_session", true);` is enough to force a new session.
> Sdk 869/resume state not working

- src/scripts/android/updateAndroidManifest.js
Client had already submitted a PR for this (https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/625) but we needed to remove the manifest entry if it exists not just stop adding it (so users don't have to remove and add back in the android platform when they upgrade the plugin). In the interest of a timely release, I went ahead created a new PR rather than requesting changes on the existing one.
> INTENG-9081/remove install referrer broadcast receiver entry

- src/index.js
- src/ios/BranchSDK.h
- src/ios/BranchSDK.m
- src/scripts/android/updateAndroidManifest.js
- src/scripts/ios/updateAssociatedDomains.js
- src/scripts/ios/updatePlist.js
- src/scripts/npm/processConfigXml.js
1. Add a wrapper function for the iOS session restart function to enable handling a Branch link from within the app
2. Enable the ability to add platform-specific domains. Allow to add platform-specific domains by using a <android link-domain> or <ios link-domain> tags
3. Replace <branch-key> tag in config.xml with <branch-key-live>, <branch-key-test>, and a boolean <branch-test-mode>.
> Cordova Feature Requests - iOS Session Override + Platform-specific Domains - SDK-593

- src/android/io/branch/BranchSDK.java
Android bug: Calling `sendBranchEvent` without metaData fails.
Solution: add a handler function for this case.
> fix(android): sendBranchEvent single parameter

- src/scripts/hooks/beforePrepare.js
- src/scripts/ios/updateHeaderPaths.js
Some plugins still use the old CocoaPods way to resolve config dirs or other obscure ways that modify CocoaPods config. That causes the Branch plugin to fail on iOS build.
Solution:
Create a hook that adds some extra config to CocoaPods and avoid being affected by other plugins overriding CocoaPods config.
> Add branch header search paths to cocoapods config

- src/scripts/ios/updateHeaderPaths.js
Native iOS SDK 0.35.0 has a new folder structure consisting of a flat folder `Branch/Branch-SDK `
This PR uses the new Path to include a HEADER_SEARCH_PATHS entry in case the default CocoaPods config is changed by other plugin(s).
Related issues:
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/642
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/662
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/602
> Update header search paths to match new iOS folder structure

- CHANGELOG.md
- package.json
- plugin.xml
- src/android/io/branch/BranchSDK.java
- src/index.js
- src/ios/BranchSDK.h
- src/ios/BranchSDK.m
Update dependencies, including native iOS and Android versions.
> SDK-1440 update dependencies

- CHANGELOG.md
- package.json
- plugin.xml
- src/android/io/branch/BranchSDK.java
QSS-265 --Unable to receive proper response from SDK to read the logs while creating deep link for Cordova
When the JS Branch.setLogging is called, it is defined to send the command “enableLogging” to the native plugin layer: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/blob/master/src/index.js#L128
However, the native plugin layer is expecting the command “setLogging”
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/blob/master/src/android/io/branch/BranchSDK.java#L122
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/blob/master/src/android/io/branch/BranchSDK.java#L1236
This PR changes the value of the string to match what's being sent from the JS layer, as well as a …
> Fix setLogging to enable logging in native layer

- package.json
- src/__tests__/index.js
- src/android/io/branch/BranchSDK.java
- src/index.js
- src/ios/BranchSDK.h
- src/ios/BranchSDK.m
- src/scripts/examples/templates/cordova1/index.html
- src/scripts/examples/templates/cordova1/index.js
SDK-2058 -- Remove v1/event code
Removed deprecated v1/events `userCompletedAction` and `sendCommerceEvent` code from `BranchSDK.java`, `BranchSDK.h` and `BranchSDK.m`, and `index.js`, as well as from the sample apps. The changes are published in npm under the alpha package `5.2.1-alpha.0`.
Remove old code that has been deprecated for a sufficient amount of time.
Add the alpha package (`5.2.1-alpha.0`) to your app, or run the examples and ensure all functionality is still working.
> [SDK-2058] Remove v1/event code

- CHANGELOG.md
- package.json
- plugin.xml
SDK-2174 -- Bump iOS SDK to 3.0.0 and Android SDK to 5.7.5
Updated the native SDK versions.
Keep the plugins up to date with our native SDKs.
Run a sample app on iOS and Android using the 6.0.0-alpha.0 version of the SDK.
> [SDK-2174] Updated iOS SDK version to 3.0.0 and Android to 5.7.5

- CHANGELOG.md
- package.json
- plugin.xml
- src/android/io/branch/BranchSDK.java
- src/index.js
- src/ios/BranchSDK.h
- src/ios/BranchSDK.m
SDK-2253 -- Expose the setDMAParamsForEEA method
Expose the setDMAParamsForEEA method in the JS layer and bump the native SDK versions.
So clients can utilize the method in Cordova and stay compliant.
1. In a test app, install the `branch-cordova-sdk@6.1.0-alpha.6` to get the latest version of our SDK with the new method.
2. Call the method like `Branch.setDMAParamsForEEA(true, true, true);` 
3. Observe the following request payloads for the respective DMA fields; `dma_eea, dma_ad_personalization, dma_ad_user_data` . 
> [SDK-2253] Expose the setDMAParamsForEEA method

- CHANGELOG.md
- package.json
- plugin.xml
SDK-2446 -- Updated plugin.xml to Specify Minimum iOS Deployment Target
Updated the Branch iOS SDK to 3.4.3 and the Android SDK to 5.12.0. Also added a deployment target for iOS 12 to fix a build error faced by some clients.
Provide updated native SDK features to clients and fix a build issue.
Integrate the Cordova plugin into a test app via the npm alpha package: `6.2.0-alpha.0`. Ensure that the Android and iOS version especially build properly.
> [SDK-2446] Updated Native SDK versions and added iOS deployment target
